openapi: 3.0.3
info:
  title: payments-api
  version: 1.0.0
  description: REST API OpenAPI documentation for the payments-api
paths:
  /payments/credit_cards:
    get:
      operationId: list credit cards
      description: List all credit cards owned by your account.
      summary: List of the credit cards
      parameters:
      - in: query
        name: fields
        schema:
          type: string
        description: Comma-separated list of field names to include in the response.
      - name: ordering
        required: false
        in: query
        description: |-
          Which field to use when ordering the results.
          (Valid fields: id, card_holder, card_brand, card_expiration_month, card_expiration_year, card_last_4_digits, card_address_zip, card_country, card_address_line1, card_address_line2, stripe_token, card_id, is_default)
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: page_size
        schema:
          type: integer
        description: A numeric value that indicates the number of items per page.
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - Billing & Payments
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPaymentMethodResponseList'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
    post:
      operationId: create credit card
      description: Create a new credit card for your account.
      summary: Create a new credit card
      tags:
      - Billing & Payments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentMethodRequest'
        required: true
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
          description: ''
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
  /payments/credit_cards/{id}:
    get:
      operationId: retrieve credit card
      description: Retrieve details from a specific credit card in your account.
      summary: Retrieve details from a credit card
      parameters:
      - in: query
        name: fields
        schema:
          type: string
        description: Comma-separated list of field names to include in the response.
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - Billing & Payments
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
    patch:
      operationId: partial update credit card
      description: Update the field 'is_default' to enable of an existing credit card.Only
        the field 'is_default' is editable for an existing card.
      summary: Partially update a credit card
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - Billing & Payments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPartialUpdateRequest'
            examples:
              PartialUpdateExample:
                value:
                  is_default: true
                summary: Example of partial update request body
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
              examples:
                PartialUpdateResponseExample:
                  value:
                    state: executed
                    data:
                      id: 0
                      card_holder: string
                      card_brand: string
                      card_expiration_month: 12
                      card_expiration_year: 2099
                      card_last_4_digits: '1234'
                      card_address_zip: string
                      card_country: string
                      card_address_line1: string
                      card_address_line2: string
                      card_id: string
                      is_default: true
                  summary: Example of partial update response body
          description: ''
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
    delete:
      operationId: destroy credit card
      description: Destruction of a specific credit card in your account.
      summary: Destroy a credit card
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - Billing & Payments
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: ''
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
  /payments/credits:
    post:
      operationId: add credits
      description: Add credit into the default credit card in US Dollars.
      summary: Add credits using the default credit card
      tags:
      - Billing & Payments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
        required: true
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
              examples:
                ResponseExample:
                  value:
                    state: executed
                    data:
                      client_id: string
                      currency: string
                      entry_type: string
                      amount: '12.75'
                      expiration_date: string
                      created: string
                      customer_stripe_id: string
                      description: string
                  summary: Response example
                  description: This is the response format for a successful credit
                    creation.
          description: ''
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
  /payments/history:
    get:
      operationId: list payment history
      description: List all details of the payment history.
      summary: List of the payment history
      parameters:
      - in: query
        name: fields
        schema:
          type: string
        description: Comma-separated list of field names to include in the response.
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - Billing & Payments
      security:
      - TokenAuth: []
      - BearerAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPaymentHistoryList'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10001:
                  value:
                    errors:
                    - status: '401'
                      code: '10001'
                      title: Authentication Failed
                      detail: Invalid authentication credentials.
                  summary: Authentication Failed
                  description: Invalid authentication credentials.
          description: Authentication Failed
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10003:
                  value:
                    errors:
                    - status: '403'
                      code: '10003'
                      title: Permission Denied
                      detail: You do not have permission to perform this action.
                  summary: Permission Denied
                  description: You do not have permission to perform this action.
          description: Permission Denied
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10000:
                  value:
                    errors:
                    - status: '400'
                      code: '10000'
                      title: Validation Error
                      detail: Invalid data provided in the request.
                  summary: Validation Error
                  description: Invalid data provided in the request.
          description: Validation Error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10004:
                  value:
                    errors:
                    - status: '404'
                      code: '10004'
                      title: Not Found
                      detail: Not found.
                  summary: Not Found
                  description: Not found.
          description: Not Found
        '405':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10007:
                  value:
                    errors:
                    - status: '405'
                      code: '10007'
                      title: Method Not Allowed
                      detail: Method "{method}" not allowed.
                  summary: Method Not Allowed
                  description: Method "{method}" not allowed.
          description: Method Not Allowed
        '406':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10005:
                  value:
                    errors:
                    - status: '406'
                      code: '10005'
                      title: Not Acceptable
                      detail: Could not satisfy the request Accept header.
                  summary: Not Acceptable
                  description: Could not satisfy the request Accept header.
          description: Not Acceptable
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONAPIErrorResponse'
              examples:
                Error-10010:
                  value:
                    errors:
                    - status: '429'
                      code: '10010'
                      title: Throttled
                      detail: Request was throttled.
                  summary: Throttled
                  description: Request was throttled.
          description: Throttled
components:
  schemas:
    Credit:
      type: object
      properties:
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
        client_id:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
        currency:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
        entry_type:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
        expiration_date:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
        created:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
        customer_stripe_id:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
        description:
          type: string
          readOnly: true
          maxLength: 255
          minLength: 1
      required:
      - amount
      - client_id
      - created
      - currency
      - customer_stripe_id
      - description
      - entry_type
      - expiration_date
      title: Credit
      additionalProperties: false
    CreditRequest:
      type: object
      properties:
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,6}(?:\.\d{0,2})?$
      required:
      - amount
      title: CreditRequest
      additionalProperties: false
    CreditResponse:
      type: object
      properties:
        state:
          type: string
          default: executed
          pattern: .*
          maxLength: 8
          minLength: 1
        data:
          $ref: '#/components/schemas/Credit'
      required:
      - data
      title: CreditResponse
      additionalProperties: false
    DeleteResponse:
      type: object
      properties:
        state:
          type: string
          default: executed
          pattern: .*
          maxLength: 8
          minLength: 1
      title: DeleteResponse
      additionalProperties: false
    JSONAPIErrorObject:
      type: object
      description: Serializer for a single JSON:API error object.
      properties:
        status:
          type: string
          description: The HTTP status code applicable to this problem
          pattern: ^\d{3}$
          maxLength: 3
          minLength: 3
        code:
          type: string
          description: An application-specific error code
          pattern: ^\d{5}$
          maxLength: 5
          minLength: 5
        title:
          type: string
          description: A short, human-readable summary of the problem
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of
            the problem
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
        source:
          allOf:
          - $ref: '#/components/schemas/JSONAPIErrorSource'
          description: References to the primary source of the error
        meta:
          type: object
          additionalProperties: {}
          description: Non-standard meta-information about the error
      title: JSONAPIErrorObject
      additionalProperties: false
    JSONAPIErrorResponse:
      type: object
      description: Serializer for a JSON:API error response.
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/JSONAPIErrorObject'
          description: Array of error objects
      required:
      - errors
      title: JSONAPIErrorResponse
      additionalProperties: false
    JSONAPIErrorSource:
      type: object
      description: Serializer for the 'source' object in a JSON:API error.
      properties:
        pointer:
          type: string
          description: JSON Pointer to the value in the request document that caused
            the error
          pattern: ^(/[^/]+)+$
          maxLength: 4096
          minLength: 1
        parameter:
          type: string
          description: URI query parameter that caused the error
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
        header:
          type: string
          description: Request header name that caused the error
          pattern: ^.*$
          maxLength: 4096
          minLength: 1
      title: JSONAPIErrorSource
      additionalProperties: false
    PaginatedPaymentHistoryList:
      type: object
      properties:
        count:
          type: integer
          minimum: 0
          maximum: 2147483647
          example: 123
          description: Total number of items
        total_pages:
          type: integer
          minimum: 1
          maximum: 2147483647
          example: 10
          description: Total number of pages
        page:
          type: integer
          minimum: 1
          maximum: 2147483647
          example: 1
          description: Current page number
        page_size:
          type: integer
          minimum: 1
          maximum: 100
          example: 10
          description: Number of items per page
        next:
          type: string
          nullable: true
          format: uri
          example: https://api.example.com/items?page=3
          description: URL to the next page of results
        previous:
          type: string
          nullable: true
          format: uri
          example: https://api.example.com/items?page=1
          description: URL to the previous page of results
        results:
          type: array
          items:
            $ref: '#/components/schemas/PaymentHistory'
      title: PaginatedPaymentHistoryList
      additionalProperties: false
    PaginatedPaymentMethodResponseList:
      type: object
      properties:
        count:
          type: integer
          minimum: 0
          maximum: 2147483647
          example: 123
          description: Total number of items
        total_pages:
          type: integer
          minimum: 1
          maximum: 2147483647
          example: 10
          description: Total number of pages
        page:
          type: integer
          minimum: 1
          maximum: 2147483647
          example: 1
          description: Current page number
        page_size:
          type: integer
          minimum: 1
          maximum: 100
          example: 10
          description: Number of items per page
        next:
          type: string
          nullable: true
          format: uri
          example: https://api.example.com/items?page=3
          description: URL to the next page of results
        previous:
          type: string
          nullable: true
          format: uri
          example: https://api.example.com/items?page=1
          description: URL to the previous page of results
        results:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMethodResponse'
      title: PaginatedPaymentMethodResponseList
      additionalProperties: false
    PatchedPartialUpdateRequest:
      type: object
      properties:
        is_default:
          type: boolean
      title: PatchedPartialUpdateRequest
      additionalProperties: false
    PaymentHistory:
      type: object
      properties:
        amount_with_currency:
          type: string
          pattern: .*
          maxLength: 50
          minLength: 1
        invoice_number:
          type: string
          nullable: true
          pattern: .*
          maxLength: 100
          minLength: 1
        invoice_url:
          type: string
          nullable: true
          pattern: ^/account/\d+/invoice\?billing_month=\d{4}-\d{2}$
          maxLength: 100
          minLength: 1
        status:
          type: string
          pattern: ^[\w\s]*$
          maxLength: 30
          minLength: 1
        payment_due:
          type: string
          format: date
        card_brand:
          type: string
          nullable: true
          pattern: ^[\w\s]*$
          maxLength: 50
          minLength: 1
        payment_method_details:
          type: string
          nullable: true
          pattern: .*
          maxLength: 255
          minLength: 1
      required:
      - amount_with_currency
      - card_brand
      - invoice_number
      - invoice_url
      - payment_due
      - payment_method_details
      - status
      title: PaymentHistory
      additionalProperties: false
    PaymentMethod:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        card_holder:
          type: string
          pattern: ^[a-zA-Z ]+$
          maxLength: 255
          minLength: 1
        card_brand:
          type: string
          pattern: ^[a-zA-Z ]+$
          maxLength: 50
          minLength: 1
        card_expiration_month:
          type: integer
          maximum: 12
          minimum: 1
        card_expiration_year:
          type: integer
          maximum: 2099
          minimum: 2022
        card_last_4_digits:
          type: string
          pattern: ^\d{4}$
          maxLength: 4
          minLength: 4
        card_address_zip:
          type: string
          pattern: ^[\w\s-]+$
          maxLength: 20
          minLength: 1
        card_country:
          type: string
          pattern: ^[a-zA-Z ]+$
          maxLength: 100
          minLength: 1
        card_address_line1:
          type: string
          pattern: .*
          maxLength: 255
          minLength: 1
        card_address_line2:
          type: string
          pattern: .*
          maxLength: 255
          minLength: 1
        card_id:
          type: string
          pattern: .*
          maxLength: 255
          minLength: 1
        is_default:
          type: boolean
      required:
      - card_address_zip
      - card_brand
      - card_country
      - card_expiration_month
      - card_expiration_year
      - card_holder
      - card_id
      - card_last_4_digits
      - id
      title: PaymentMethod
      additionalProperties: false
    PaymentMethodRequest:
      type: object
      properties:
        card_holder:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z ]+$
          maxLength: 255
        card_brand:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z ]+$
          maxLength: 50
        card_expiration_month:
          type: integer
          maximum: 12
          minimum: 1
        card_expiration_year:
          type: integer
          maximum: 2099
          minimum: 2022
        card_last_4_digits:
          type: string
          minLength: 4
          pattern: ^\d{4}$
          maxLength: 4
        card_address_zip:
          type: string
          minLength: 1
          pattern: ^[\w\s-]+$
          maxLength: 20
        card_country:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z ]+$
          maxLength: 100
        card_address_line1:
          type: string
          minLength: 1
          pattern: .*
          maxLength: 255
        card_address_line2:
          type: string
          minLength: 1
          pattern: .*
          maxLength: 255
        stripe_token:
          type: string
          writeOnly: true
          minLength: 1
          pattern: .*
          maxLength: 255
        card_id:
          type: string
          minLength: 1
          pattern: .*
          maxLength: 255
        is_default:
          type: boolean
      required:
      - card_address_zip
      - card_brand
      - card_country
      - card_expiration_month
      - card_expiration_year
      - card_holder
      - card_id
      - card_last_4_digits
      - stripe_token
      title: PaymentMethodRequest
      additionalProperties: false
    PaymentMethodResponse:
      type: object
      properties:
        state:
          type: string
          default: executed
          pattern: .*
          maxLength: 8
          minLength: 1
        data:
          $ref: '#/components/schemas/PaymentMethod'
      required:
      - data
      title: PaymentMethodResponse
      additionalProperties: false
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
